all: compile link run


compile:
	g++ -c main.cpp -I"C:\Users\User\Downloads\SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit\SFML-2.5.1\include"

link:
	g++ main.o -o sfml-app -L"g++ main.o -o sfml-app -L"C:\Users\User\Downloads\SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit\SFML-2.5.1\lib" -lsfml-graphics -lsfml-window -lsfml-system -lsfml-network -lsfml-audio
run:

	.\sfml-app